"""app/validation.py — Helpers for validating simulation grid sizes and inputs."""

import streamlit as st

# Thresholds for grid validation
MAX_SAFE_POINTS = 500_000
MAX_ADVANCED_POINTS = 2_500_000

def estimate_binary_grid_points(phiC_min: float, phiC_max: float, dphiC: float) -> int:
    """Estimate the number of grid points for a 1D binary simulation."""
    if dphiC <= 0:
        return 0
    return int((phiC_max - phiC_min) / dphiC) + 1

def estimate_ternary_grid_points(phi2_min: float, phi2_max: float, dphi2: float, 
                                 phi3_min: float, phi3_max: float, dphi3: float) -> int:
    """Estimate the number of grid points for a 2D ternary simulation."""
    if dphi2 <= 0 or dphi3 <= 0:
        return 0
    n2 = int((phi2_max - phi2_min) / dphi2) + 1
    n3 = int((phi3_max - phi3_min) / dphi3) + 1
    return n2 * n3

def validate_grid_size(n_points: int, is_advanced: bool, num_arrays: int = 10):
    """
    Validate that the grid size is within safe memory limits.
    Stops Streamlit execution if limits are exceeded.
    
    Args:
        n_points: Estimated number of grid points.
        is_advanced: Whether the user has opted into advanced high-resolution mode.
        num_arrays: Estimated number of float64 arrays generated by the model.
    """
    # Rough memory estimate: 8 bytes per float64 * number of arrays * grid size
    mem_bytes = n_points * 8 * num_arrays
    mem_mb = mem_bytes / (1024 * 1024)
    
    if is_advanced:
        threshold = MAX_ADVANCED_POINTS
    else:
        threshold = MAX_SAFE_POINTS
        
    if n_points > threshold:
        st.error(f"**Grid Size Too Large!**\n\n"
                 f"Your current settings will generate approximately **{n_points:,} points** "
                 f"(~{mem_mb:.1f} MB core memory), which exceeds the safe limit of **{threshold:,}**.\n\n"
                 f"**How to fix:**\n"
                 f"- Increase the grid step size (`Δϕ`)\n"
                 f"- Decrease the maximum volume fraction (`ϕ max`)\n"
                 f"- If you really need this resolution, enable 'Advanced / High-Resolution Grid' in the sidebar.")
        st.stop()
        
    return n_points, mem_mb

def check_ternary_composition(phi2_max: float, phi3_max: float):
    """Ensure that the maximum volume fractions do not leave zero room for solvent."""
    total_phi = phi2_max + phi3_max
    if total_phi >= 0.99:
        st.error(f"**Invalid Composition!**\n\n"
                 f"The maximum volume fractions for cosolute 2 and 3 sum up to {total_phi:.2f}. "
                 f"This leaves less than 1% for the solvent, which is unphysical and may cause numerical instability.\n\n"
                 f"**How to fix:**\n"
                 f"- Reduce `ϕ₂ max` or `ϕ₃ max` so their sum is strictly less than 0.99.")
        st.stop()
